<p>Jak může laskavý čtenář vidět dole, pod tímto textem, mám již připravený k vydání šestý díl cyklu Paměti krupiérovy / Mémoires d'un croupier Gang, který nikdy neexistoval. Tento díl jsem již celý dokončil, dokonce jsem ho nechal i (několikrát) zkušebně vytisknout, nechal jsem vytisknou takzvaný „nátisk“, to jest tedy zkušební jeden výtisk knihy, kterou chcete vydat. Mám již od pátého dílu zřízenou vlastní živnost na nakladatelství, jsem tedy nakladatel. Žádné nakladatelství mi moje knihy nevydá, musel jsem se tedy nakladatelem stát sám. Rozhodně toho ale nelituji. Příslušný úřad mi přidělil řadu ISBN, nežádám nyní o přidělení ISBN před vydáním každého dílu.</p>
<p>Nyní k šestému dílu Pamětí. Nikdy jsem se netajil svým odporem k současnému českému soudnímu systému. Nikdy jsem se netajil mým odporem k velkému množství osob, které v české justici působí. Mnoho z nich je bývalých komunistů, mnoho z nich bylo „soudci“ i za bolševického režimu, toho nejhoršího režimu, jaký v naší krásné zemi existoval. Komunistický režim byl do naší země zavlečen Sovětským svazem a tento Sovětský svaz byl od roku 1968 přímou okupační mocností Československa. Kdo byl tedy před rokem 1989 členem komunistické strany, tak se nejenom, že podílel na útlaku lidí, byl ale přímo vlastizrádcem a kolaborantem se Sovětským svazem. Nyní jsou bývalí komunisté v čele velkých, možno říci důležitých soudů. Bývalý komunista je předsedou soudu ústavního, druhý komunista je šéfem soudu nejvyššího a třetí komunista je předsedou soudu nejvyššího správního. Bývalý komunista je presidentem republiky, jiný bývalý komunista je předseda vlády. </p>
<p>Šestý díl začíná představením několika bývalých komunistů, kteří stále působí v české justici. Laskavý čternář se seznámí s příběhem bývalého komunisty, který zatajil svoje členství v této zločinecké organizaci, soudil se se státem o milionové částky, za to, že určitou dobu dojížděl k jinému soudu, než dříve. Tento bývalý komunista nahlížel mnohokráte do soudního spisu, který nebyl přidělený mu a do kterého nebyl oprávněn nahlížet. </p>
<p>Laskavý čtenář se dočte o mladém kudrnáčkovi, soudci, který poslal udání na velmi solidní soudkyni, se kterou seděl několik let v jedné kanceláři. Ve svém udavačském dopise navrhoval, aby vedení soudu na tuto soudkyni podalo kárnou žalobu za to, že v absolutní přetíženosti napsala jednomu žadateli o obnovu řízení, že v této chvíli má strašně moc práce a je možné, že se k jeho případu dostane až za delší dobu. Dovedete si to předstvit? Být udavačem? Práskačem? Bonzákem? </p>
<p>V další části knihy se dostaneme do úplně jiné reality. Na scému přichází Milostivá slečna, noblesní dáma z minulosti, se svým malým dvorem, se kterým přichází na tento svět, do této doby – až z Říše zapomění. Laskavý čtenář se seznámí s Milostivou slečnou, která je protipólem udavačského kudrnáčka a jemu podobných. Kdo je poněkud slabší povaha, vadí mu Záhrobí, hrobky, podzemní vody, tajné vchody, ať o Milostivé slečně raději nic nečte. Zde jsem nucen ale prozradit něco ze vzdálenější budoucnosti. Pravý čas Milostivé slečny stále ještě nepřišel. Ten přijde až později, nejdříve v díle sedmém a snad ještě i o něco později.....</p>
<p>Kudrnatý udavač i soudce soudící se se státem o miliony zaslouží oba opovržení. Je pravda, že v současné době vydělávají velké peníze, mohou uškodit mnoha lidem, přesně těm, kteří se dostanou do jejich moci. To je však vše. Viděl jsem už mnoho bývalých komunistů, kteří škodili, vydělávali velké peníze a nyní jsou v důchodě, ani ten příslovečný pes po nich neštěkne. Neumí nic, nemají moc peněz, někteří chodí oblečení jako vandráci, ke kterým vlastně ani moc daleko nemají. Že by uměli třeba nějaké jazyky? Francouzsky? Dovolte, abych se zasmál. Aspoň anglicky? Nebo aspoň takovou tu jednoduchou angličtinu, co s ní nyní mluví Rusové, Maďaři, Řekové...... Ale kdepak, takový udavač kudrnáček neumí žádný jazyk. Co dovede, je udávat. Práskat. Je to žalobníček, takový ten, co jste ho neměli rádi na základní škole – na základce. Je to bývalý svazák, rád zdůrazňuje, že vychodil jakési prestižní gymnásium. Co je na tom gymnásiu tak prestižního? Co se tam tak naučil, když by si v Londýně nebo v Paříži nebo ve Vídni nekoupil ani noviny? I když na co by si je kupoval, když by jim stejně nerozuměl? Možná by se díval na obrázky.....</p>
<p>Vy ale vězte hodně, znejte hodně. Učte se jazyky, pak nebudete odkázaní na současnou vládnoucí garnituru a jejich sdělovací prostředky. Dnes je doba internetu a ten již tak ovládat nemohou. Nemohou cenzurovat každé video, každý článek. V další části šestého dílu proto nabízím několik rad, či poznatků, jak vylepšit svoji znalost angličtiny. Samozřejmě, jsou to jenom takové střípky, ale něco laskavému čternáři dají. Přečtěte si zde něco – a snad vám to něco dá. </p>

<p>Pamatujte si, velký příběh přijde v díle sedmém, který se velmi intenzivně chystá. Přečtěte si ale napřed i díl šestý, neboť díl sedmý bude navazovat, zde nebude možné znovu vše opakovat, vysvětlovat, jak je to vlastně s Milostivou slečnou a tak. </p>

<p>Jinak přeji moc krásné léto a vše nejlepší napořád. </p>

<p>V Brně koncem července 2019</p>

<p>JUDr. Oldřich Ševčík</p>
